### ISSUE TITLE
"hw_rng_model: virtio" for all images in openstack-image-manager

### ISSUE THREAD

**Issue by linwalth** [osism/openstack-image-manager#287] opened 2022-07-01 08:58 UTC
https://github.com/osism/openstack-image-manager/blob/main/etc/images.yml has hw_rng_model: virtio only set for ubuntu images. I suspect this should be a property of all images by now.

**Comment by berendt** [comment] 2022-08-02 14:08
Duplicate of #96

**Closed by berendt** 2022-08-02 14:08 UTC
