### ISSUE TITLE
Integrate openstack-image-manager Mirroring into Swift/RGW

### ISSUE THREAD

**Issue by linwalth** [osism/openstack-image-manager#288] opened 2022-07-01 16:43 UTC
The openstack-image-manager currently uses Minio to mirror short-lived image builds for the long run. Since OSISM deploys Ceph and S3-like APIs are standard issue in a cloud environment (As well as Minio being able to also serve S3-compatible storage), the image-manager usability would profit immensely from mirroring images in an S3-compatible way.

**Comment by berendt** [comment] 2022-08-03 07:31
Duplicate of #302

**Closed by berendt** 2022-08-03 07:31 UTC
